learning_templates/basic_app/urls.py
from django.conf.urls import url,include
from basic_app import views


app_name = 'basic_app'

urlpatterns= [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^others/$',views.others,name='others'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'Hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def others(request):
    return render(request,'basic_app/others.html')


def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:others' %}">Other</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class=""container>
        {% block body_block %}
        <!--        Anything outside this will be inherited-->
        <div class="row align-items-md-stretch">
            <div class="col-md-6">
                <div class="h-100 p-5 text-white bg-dark rounded-3">
                  <h2>Welcome to Base</h2>
<!--                  <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>-->
<!--                  <button class="btn btn-outline-light" type="button">Example button</button>-->
                </div>
            </div>
        </div>

        {% endblock %}
    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% load my_extras %}
    {% block body_block %}
        <div class="row align-items-md-stretch">

            <div class="p-5 mb-4 bg-success rounded-3">
                  <div class="container-fluid py-5">
                    <h1 class="display-5 text-white fw-bold">Welcome to HomePage!!!</h1>
                    <p class="col-md-8 text-white fs-4">This is my First HomePage!!!. Welcome to Sunder's Portal</p>

                      <h3 class="col-md-8 text-white fs-4">{{ text|cut:'world' }}</h3>
                      <br>
                      <h3 class="col-md-8 text-white fs-4">{{ number|add:"99" }}</h3>
                    <button class="btn btn-primary btn-lg" type="button">Click to Sign In!</button>
                  </div>
            </div>

        </div>
    {% endblock %}

learning_templates/templates/basic_app/others.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcom to Other!</h1>
        <h2>This is an example of template Inheritance!!!</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="row align-items-md-stretch">

            <div class="p-5 mb-4 bg-success rounded-3">
                  <div class="container-fluid py-5">
                    <h1 class="display-5 text-white fw-bold">WELCOME TO RELATIVE URL TEMPLATES!</h1>
                    <p class="col-md-8 text-white fs-4">This is my First HomePage!!!. Welcome to Sunder's Portal</p>
                    <button class="btn btn-outline-dark btn-lg" type="button" href="{% url 'basic_app:others' %}">THE OTHER PAGE</button>
                      <br><br>
                    <button class="btn btn-outline-light btn-lg" type="button" href="{% url 'admin:index' %}">ADMIN</button>
                      <br><br>
                    <button class="btn btn-warning btn-lg" type="button" href="{% url 'index' %}">Go To HomePage</button>
                  </div>
            </div>

        </div>
{% endblock %}


<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>RELATIVE URL</title>-->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">-->
<!--    &lt;!&ndash; JavaScript Bundle with Popper &ndash;&gt;-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>-->
<!--    <a class="btn btn-outline-warning btn-arrow-right"  href="{% url 'basic_app:others' %}" role="button">THE OTHER PAGE</a>-->
<!--    <br>-->
<!--    <br>-->
<!--    <a class="btn btn-secondary btn-arrow-right"  href="{% url 'admin:index' %}" role="button">ADMIN</a>-->
<!--&lt;!&ndash;    <a href="{% url 'basic_app:others' %}">THE OTHER PAGE</a>&ndash;&gt;-->

<!--    <br>-->
<!--    <br>-->
<!--    <a class="btn btn-secondary btn-arrow-left"  href="{% url 'index' %}" role="button">Go To HomePage</a>-->
<!--</body>-->
<!--</html>-->